apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volume-container
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /C/primeiro-volume
        type: Directory